drop index region_shape;
drop index lion_location;
drop index pond_shape;
drop index ambulance_coverArea;
delete from user_sdo_geom_metadata;
drop table region;
drop table lion;
drop table pond;
drop table ambulance;
